'use client'
import { useMemo,useRef,useState } from 'react'
import { useRouter } from 'next/navigation'
import PortalHeader from '@/components/shared/PortalHeader'
import { createProfile,setActiveProjectId } from '@/lib/user-profile-store'
import { addOrder,createProjectOrder } from '@/lib/order-store'
import type { DrawingSource, FamilyPlan, HouseholdType, SingleGender, UserProfile } from '@/lib/types'

const MAX=15*1024*1024
function drawingFromFile(file:File,previewDataUrl?:string):DrawingSource{return{id:`DRAW-${Date.now()}`,source:'upload',fileName:file.name,fileType:file.type||'application/octet-stream',fileSize:file.size,importedAt:new Date().toISOString(),templateId:'HOUSE_001',parserMode:'demo-template',previewDataUrl,detected:{rooms:6,walls:9,doors:5,windows:10}}}
function demoDrawing():DrawingSource{return{id:`DRAW-DEMO-${Date.now()}`,source:'demo',fileName:'HOUSE_001_demo_floorplan.pdf',fileType:'application/pdf',fileSize:0,importedAt:new Date().toISOString(),templateId:'HOUSE_001',parserMode:'demo-template',detected:{rooms:6,walls:9,doors:5,windows:10}}}

export default function SetupFlow(){
  const router=useRouter(),inputRef=useRef<HTMLInputElement>(null)
  const[step,setStep]=useState<1|2|3>(1),[drawing,setDrawing]=useState<DrawingSource|null>(null),[preview,setPreview]=useState(''),[parseProgress,setParseProgress]=useState(0),[error,setError]=useState('')
  const[name,setName]=useState(''),[household,setHousehold]=useState<HouseholdType>('single'),[gender,setGender]=useState<SingleGender>('male'),[familyPlan,setFamilyPlan]=useState<FamilyPlan>('child'),[workFromHome,setWorkFromHome]=useState(false),[storagePriority,setStoragePriority]=useState<'normal'|'high'>('normal'),[style,setStyle]=useState<UserProfile['preferredStyle']>('modern')
  const scenario=useMemo(()=>household==='single'?(gender==='female'?'single_female':'single'):household==='couple'?'couple':familyPlan==='nanny'?'nanny':'child',[household,gender,familyPlan])
  async function acceptFile(file:File){setError('');if(file.size>MAX){setError('文件不能超过15MB');return}if(!['image/png','image/jpeg','application/pdf'].includes(file.type)){setError('仅支持 PNG / JPG / PDF');return}let data='';if(file.type.startsWith('image/')&&file.size<2*1024*1024){data=await new Promise<string>(r=>{const fr=new FileReader();fr.onload=()=>r(String(fr.result||''));fr.readAsDataURL(file)})}setPreview(data);setDrawing(drawingFromFile(file,data||undefined))}
  async function parse(){if(!drawing)return;setStep(3);for(const p of [18,38,61,82,100]){await new Promise(r=>setTimeout(r,220));setParseProgress(p)}setStep(2)}
  function create(){if(!drawing||!name.trim())return;const profile=createProfile({displayName:name.trim(),household,singleGender:household==='single'?gender:undefined,familyPlan:household==='family3'?familyPlan:undefined,workFromHome,storagePriority,preferredStyle:style});const order=createProjectOrder({customer:profile.displayName,userProfileId:profile.id,drawing,scenario});addOrder(order);setActiveProjectId(order.id);router.push('/customer/')}
  return <main className="setup-page"><PortalHeader title="住户初始设置" subtitle="Resident Setup"/><div className="setup-wrap"><div className="setup-steps"><span className={step===1?'active':''}>1 图纸导入</span><span className={step===3?'active':''}>2 图纸解析</span><span className={step===2?'active':''}>3 用户画像</span></div>
    {step===1&&<section className="setup-card"><h1>导入住宅二维图纸</h1><p>Demo阶段真实接收文件和预览，解析结果映射到当前 HOUSE_001 模板；后续可直接替换为图纸识别服务。</p><div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const f=e.dataTransfer.files[0];if(f)acceptFile(f)}} onClick={()=>inputRef.current?.click()}><b>{drawing?drawing.fileName:'拖拽图纸到这里，或点击选择'}</b><span>PNG / JPG / PDF · 最大15MB</span><input ref={inputRef} hidden type="file" accept="image/png,image/jpeg,application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f)acceptFile(f)}}/></div>{preview&&<img className="drawing-preview" src={preview} alt="drawing preview"/>}{drawing&&<div className="drawing-meta"><span>模板：HOUSE_001</span><span>解析模式：Demo Template</span></div>}{error&&<p className="error">{error}</p>}<div className="setup-actions"><button onClick={()=>{setDrawing(demoDrawing());setPreview('')}}>使用示例图纸</button><button className="primary" disabled={!drawing} onClick={parse}>解析图纸并继续</button></div></section>}
    {step===3&&<section className="setup-card parsing-card"><h1>正在建立住宅空间语义</h1><div className="parse-progress"><i style={{width:`${parseProgress}%`}}/></div><ul><li className={parseProgress>=18?'done':''}>读取二维图纸</li><li className={parseProgress>=38?'done':''}>识别墙体与门窗</li><li className={parseProgress>=61?'done':''}>建立房间拓扑</li><li className={parseProgress>=82?'done':''}>映射 HouseTemplate</li><li className={parseProgress>=100?'done':''}>准备 Pascal Scene</li></ul></section>}
    {step===2&&<section className="setup-card"><h1>建立住户画像</h1><p>这些信息会进入用户信息库，并作为后续 AI 生成式设计的上下文。</p><label className="field"><span>姓名 / 称呼</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：李女士"/></label><div className="profile-block"><b>居住人数</b><div className="choice-row"><button className={household==='single'?'selected':''} onClick={()=>setHousehold('single')}>单身贵族</button><button className={household==='couple'?'selected':''} onClick={()=>setHousehold('couple')}>双人世界</button><button className={household==='family3'?'selected':''} onClick={()=>setHousehold('family3')}>三口之家</button></div></div>{household==='single'&&<div className="profile-block"><b>居住者</b><div className="choice-row"><button className={gender==='male'?'selected':''} onClick={()=>setGender('male')}>男士 · 电竞房</button><button className={gender==='female'?'selected':''} onClick={()=>setGender('female')}>女士 · 衣帽间</button></div></div>}{household==='family3'&&<div className="profile-block"><b>家庭方案</b><div className="choice-row"><button className={familyPlan==='child'?'selected':''} onClick={()=>setFamilyPlan('child')}>育儿家庭</button><button className={familyPlan==='nanny'?'selected':''} onClick={()=>setFamilyPlan('nanny')}>育儿 + 保姆</button></div></div>}<div className="profile-grid"><label><span>居家办公</span><input type="checkbox" checked={workFromHome} onChange={e=>setWorkFromHome(e.target.checked)}/></label><label><span>收纳需求</span><select value={storagePriority} onChange={e=>setStoragePriority(e.target.value as any)}><option value="normal">常规</option><option value="high">高</option></select></label><label><span>装修风格</span><select value={style} onChange={e=>setStyle(e.target.value as any)}><option value="modern">现代简约</option><option value="nordic">北欧</option><option value="new_chinese">新中式</option></select></label></div><div className="profile-summary"><span>初始方案</span><b>{scenario}</b><small>AI生成候选方案时会读取这份画像，但不会直接覆盖用户后续手工家具调整。</small></div><div className="setup-actions"><button onClick={()=>setStep(1)}>返回图纸</button><button className="primary" disabled={!name.trim()} onClick={create}>创建项目并进入设计</button></div></section>}
  </div></main>
}
