export type RoomType = "living_room" | "bedroom" | "kitchen" | "bathroom" | "balcony" | "study" | "dining_room" | "unknown";
type RoomTypePrompt = { label: string; description: string; required: string[]; forbidden: string[]; negative: string[] };

export const ROOM_TYPE_PROMPTS: Record<RoomType, RoomTypePrompt> = {
  bathroom: { label: "卫生间/浴室", description: "这是卫生间装修任务，必须生成一个功能完整、布局合理、可实际使用的卫生间，而不是只更换材质。允许重新布置全部内部卫浴设施，但必须保持建筑框架。", required: ["洗漱台或洗手盆", "镜子或镜柜", "马桶", "淋浴区或等效洗浴功能", "毛巾架、置物架、洗漱用品和卫浴收纳", "防水墙地面材质", "合理的干湿分离或明确的干湿分区"], forbidden: ["沙发", "茶几", "床", "餐桌", "电视柜", "书桌", "客厅落地灯", "休闲单椅", "客厅、卧室或书房布局"], negative: ["sofa", "couch", "coffee table", "bed", "dining table", "desk", "tv stand", "lounge chair", "living room furniture", "bedroom furniture", "沙发", "茶几", "床", "餐桌", "电视柜", "书桌", "休闲椅"] },
  kitchen: { label: "厨房", description: "这是厨房空间的装修任务，必须保持为功能正确的厨房。", required: ["橱柜", "台面", "水槽", "灶台或烹饪区", "厨房收纳", "厨房照明和耐用易清洁材质"], forbidden: ["沙发", "床", "浴缸", "马桶", "书桌", "卧室或客厅主体布局"], negative: ["sofa", "bed", "bathtub", "toilet", "study desk", "bedroom furniture", "沙发", "床", "浴缸", "马桶", "书桌"] },
  bedroom: { label: "卧室", description: "这是卧室空间的装修任务，必须保持为功能正确的卧室。", required: ["床", "床头柜", "衣柜或衣物收纳", "卧室照明", "窗帘或柔软织物"], forbidden: ["马桶", "灶台", "浴缸", "办公前台", "大型餐桌", "厨房或卫生间主体布局"], negative: ["toilet", "stove", "bathtub", "reception desk", "large dining table", "厨房", "卫生间", "马桶", "灶台"] },
  living_room: { label: "客厅/客餐厅", description: "这是客厅/客餐厅空间的装修任务，必须保持为休闲交流空间。", required: ["沙发", "茶几", "电视墙或收纳", "地毯或休闲软装", "适合交流的客厅照明"], forbidden: ["马桶", "淋浴区", "橱柜式厨房主功能布局", "卧室床位作为主体"], negative: ["toilet", "shower", "kitchen cabinet layout", "bed as the main furniture", "马桶", "淋浴区", "厨房主功能布局", "卧室床"] },
  study: { label: "书房", description: "这是书房空间的装修任务，必须保持为阅读和工作的书房。", required: ["书桌", "工作椅", "书架或书籍收纳", "阅读和工作照明"], forbidden: ["马桶", "灶台", "浴缸", "沙发作为主体", "卧室床作为主体"], negative: ["toilet", "stove", "bathtub", "sofa as main furniture", "bed as main furniture", "马桶", "灶台", "浴缸"] },
  balcony: { label: "阳台", description: "这是阳台空间的装修任务，必须保持为通风采光的阳台。", required: ["阳台栏杆或落地窗关系", "耐候地面", "少量阳台收纳或绿植"], forbidden: ["马桶", "灶台", "完整卧室床位", "完整客厅布局"], negative: ["toilet", "stove", "full bedroom bed", "full living room layout", "马桶", "灶台", "完整卧室床位"] },
  dining_room: { label: "餐厅", description: "这是餐厅空间的装修任务，必须保持为用餐空间。", required: ["餐桌", "餐椅", "餐边柜或餐具收纳", "适合用餐的照明"], forbidden: ["马桶", "淋浴区", "床", "灶台作为主体"], negative: ["toilet", "shower", "bed", "stove as main function", "马桶", "淋浴区", "床", "灶台"] },
  unknown: { label: "当前空间", description: "房间类型未能识别，仅进行保守的室内设计编辑。不得改变原始空间功能。", required: [], forbidden: ["改变原始空间功能", "重新规划建筑布局"], negative: ["different room", "changed room function", "new architectural layout", "重新规划建筑布局"] },
};

const ROOM_NAME_RULES: Array<[RegExp, RoomType]> = [[/卫生间|浴室|洗手间|卫浴|厕所|toilet|bathroom|washroom/i, "bathroom"], [/厨房|厨|kitchen/i, "kitchen"], [/主卧|次卧|卧室|儿童房|客房|bedroom|master|child/i, "bedroom"], [/客餐厅|客厅|起居室|living|lounge/i, "living_room"], [/书房|工作室|study|office/i, "study"], [/阳台|露台|balcony|terrace/i, "balcony"], [/餐厅|dining/i, "dining_room"]];
export function inferRoomType(roomName?: string | null): RoomType { const value = String(roomName || "").trim(); return value ? (ROOM_NAME_RULES.find(([pattern]) => pattern.test(value))?.[1] || "unknown") : "unknown"; }
export function buildRoomTypePrompt(roomType: RoomType, roomName?: string | null) { const config = ROOM_TYPE_PROMPTS[roomType] || ROOM_TYPE_PROMPTS.unknown; const bathroomLayout = roomType === "bathroom" ? "允许移动马桶、台盆、淋浴区、镜柜、隔断、灯具和收纳；马桶不得孤立放在空间中央，应优先沿墙布置主要卫浴设施，并尽量形成干湿分离。" : ""; return [`房间功能约束：${config.description}`, roomName?.trim() ? `当前房间名称：${roomName.trim()}。` : "", config.required.length ? `必须合理呈现的功能元素：${config.required.join("、")}。` : "", bathroomLayout, `禁止出现与该房间功能不符的内容：${config.forbidden.join("、")}。`, "房间功能优先于装修风格；风格只能改变材质、颜色、造型语言、灯光和软装，不能改变房间用途或建筑结构。"].filter(Boolean).join("\n"); }
export function roomTypeNegativePrompt(roomType: RoomType) { return (ROOM_TYPE_PROMPTS[roomType] || ROOM_TYPE_PROMPTS.unknown).negative.join(", "); }
