import fs from 'node:fs'
function assert(v,m){if(!v)throw new Error(m)}
const order=fs.readFileSync('lib/order-store.ts','utf8')
const overrides=fs.readFileSync('lib/furniture-overrides.ts','utf8')
const provider=fs.readFileSync('lib/ai/provider.ts','utf8')
const aiConfig=fs.readFileSync('lib/ai/config.ts','utf8')
const qwenAgent=fs.readFileSync('lib/ai/qwen-layout-agent.ts','utf8')
const layoutTools=fs.readFileSync('lib/layout-tools.ts','utf8')
const setup=fs.readFileSync('components/setup/SetupFlow.tsx','utf8')
const design=fs.readFileSync('components/customer/CustomerDesign.tsx','utf8')
const contractor=fs.readFileSync('components/customer/ExecutionMonitoring.tsx','utf8')
const bomTools=fs.readFileSync('lib/bom/tools.ts','utf8')
const bomService=fs.readFileSync('lib/bom/service.ts','utf8')
const bomRoute=fs.readFileSync('app/api/bom/generate/route.ts','utf8')
assert(overrides.includes('applyFurnitureOverrides'),'Furniture override re-apply missing')
assert(order.includes('captureFurnitureOverrides'),'Furniture override persistence missing')
assert(order.includes('syncOrderDownstream'),'Design → MES sync missing')
assert(order.includes('applyAiLayoutRun'),'AI layout persistence missing')
assert(aiConfig.includes("process.env.AI_PROVIDER||'mock'"),'Mock AI default missing')
assert(provider.includes('generateLayout'),'Interactive layout provider method missing')
assert(setup.includes('解析图纸并继续')&&setup.includes('建立住户画像'),'Setup flow missing')
assert(design.includes('/api/ai/layout')&&design.includes('AI SPACE AGENT'),'Interactive AI layout UI missing')
assert(design.includes('/api/ai/plans')&&design.includes('/api/ai/render'),'AI adapters not wired to design')
assert(design.includes('Pascal 3D验证')&&design.includes('进入漫游'),'Pascal verification flow missing')
assert(layoutTools.includes('get_house_constraints')&&layoutTools.includes('assign_room_function')&&layoutTools.includes('merge_rooms')&&layoutTools.includes('split_room')&&layoutTools.includes('validate_layout'),'Layout function tools missing')
assert(qwenAgent.includes('tool_calls')&&qwenAgent.includes('executeLayoutTool'),'Qwen Function Calling loop missing')
assert(contractor.includes('制造与施工监控')&&contractor.includes('拓竹3D打印机实时摄像头')&&contractor.includes('机械臂四路画面'),'MES monitoring panels missing')
console.log('Core + AI Layout integration checks: PASS')
assert(bomTools.includes('calculateWallQuantity')&&bomTools.includes('calculateFloorArea')&&bomTools.includes('createBomDraft')&&bomTools.includes('validateBom'),'Deterministic BOM tools missing')
assert(bomService.includes('enrichBom')&&bomService.includes('applyBomEnrichment'),'BOM AI enrichment chain missing')
assert(bomRoute.includes('generateDetailedBom'),'BOM API route missing')
console.log('Detailed BOM integration checks: PASS')
