import { furnitureItem } from "../house-scene";
import { buildFloorplanScene, type FloorplanSpec } from "./types";
const outer: [number, number][] = [
  [3.169, 0],
  [5.88, 0],
  [5.88, 1.282],
  [9.159, 1.282],
  [9.159, 5.715],
  [6.054, 5.715],
  [6.054, 8.134],
  [0, 8.134],
  [0, 6.485],
  [0.2, 6.485],
  [0.2, 1.282],
  [3.169, 1.282],
];
export const twoBedroomSpec: FloorplanSpec = {
  id: "two-bedroom",
  name: "二居室",
  factory: "createTwoBedroomFloorplanScene",
  sourceImage: "/preset/initial-two-bedroom.png",
  outerPolygon: outer,
  walls: [
    {
      id: "wall_outer",
      start: [3.169, 0],
      end: [5.88, 0],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_r1",
      start: [5.88, 0],
      end: [5.88, 1.282],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_r2",
      start: [5.88, 1.282],
      end: [9.159, 1.282],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_r3",
      start: [9.159, 1.282],
      end: [9.159, 5.715],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_bottom_r",
      start: [9.159, 5.715],
      end: [6.054, 5.715],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_bottom",
      start: [6.054, 5.715],
      end: [6.054, 8.134],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_bottom2",
      start: [6.054, 8.134],
      end: [0, 8.134],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_left",
      start: [0, 8.134],
      end: [0.2, 1.282],
      structural: "load_bearing",
    },
    {
      id: "wall_outer_top_l",
      start: [0.2, 1.282],
      end: [3.169, 1.282],
      structural: "load_bearing",
    },
    {
      id: "wall_living_left",
      start: [3.169, 1.282],
      end: [3.169, 6.485],
      structural: "partition",
    },
    {
      id: "wall_living_right",
      start: [5.88, 1.282],
      end: [5.88, 5.715],
      structural: "partition",
    },
    {
      id: "wall_left_bottom",
      start: [0.2, 6.485],
      end: [3.169, 6.485],
      structural: "partition",
    },
    {
      id: "wall_living_bottom",
      start: [3.169, 6.485],
      end: [6.054, 6.485],
      structural: "partition",
    },
    {
      id: "wall_bath",
      start: [0.2, 2.418],
      end: [1.887, 2.418],
      structural: "partition",
    },
  ],
  rooms: [
    {
      id: "zone_bathroom",
      name: "卫生间",
      semantic: "bathroom",
      polygon: [
        [0.2, 1.282],
        [1.887, 1.282],
        [1.887, 2.418],
        [0.2, 2.418],
      ],
      expectedArea: 2.23,
      color: "#78a4aa",
    },
    {
      id: "zone_bedroom",
      name: "主卧",
      semantic: "master_bedroom",
      polygon: [
        [0.2, 2.418],
        [3.169, 2.418],
        [3.169, 6.485],
        [0.2, 6.485],
      ],
      expectedArea: 11.04,
      color: "#8298bd",
    },
    {
      id: "zone_living",
      name: "客餐厅",
      semantic: "living_room",
      polygon: [
        [3.169, 0],
        [5.88, 0],
        [5.88, 6.485],
        [3.169, 6.485],
      ],
      expectedArea: 17.37,
      color: "#c9b989",
    },
    {
      id: "zone_bedroom_2",
      name: "次卧",
      semantic: "bedroom",
      polygon: [
        [5.88, 1.282],
        [9.159, 1.282],
        [9.159, 5.715],
        [5.88, 5.715],
      ],
      expectedArea: 13,
      color: "#91a4c2",
    },
    {
      id: "zone_kitchen",
      name: "厨房",
      semantic: "kitchen",
      polygon: [
        [0, 6.485],
        [3.727, 6.485],
        [3.727, 8.134],
        [0, 8.134],
      ],
      expectedArea: 5.21,
      color: "#9da8ab",
    },
    {
      id: "zone_balcony",
      name: "阳台",
      semantic: "balcony",
      polygon: [
        [3.727, 6.485],
        [6.054, 6.485],
        [6.054, 8.134],
        [3.727, 8.134],
      ],
      expectedArea: 3.15,
      color: "#d8d0aa",
    },
  ],
  doors: [
    {
      id: "door_entry",
      name: "入户门",
      wallId: "wall_outer",
      distance: 1.85,
      width: 1.0,
    },
    {
      id: "door_bedroom",
      name: "主卧门",
      wallId: "wall_living_left",
      distance: 2.1,
      width: 0.86,
    },
    {
      id: "door_bedroom_2",
      name: "次卧门",
      wallId: "wall_living_right",
      distance: 1.05,
      width: 0.86,
    },
    {
      id: "door_bathroom",
      name: "卫生间门",
      wallId: "wall_bath",
      distance: 1.15,
      width: 0.72,
    },
  ],
  windows: [
    {
      id: "window_master",
      name: "主卧外窗",
      wallId: "wall_left_bottom",
      distance: 1.5,
      width: 1.5,
    },
    {
      id: "window_second",
      name: "次卧外窗",
      wallId: "wall_outer_bottom_r",
      distance: 1.6,
      width: 1.5,
    },
    {
      id: "window_kitchen",
      name: "厨房外窗",
      wallId: "wall_outer_bottom2",
      distance: 1.7,
      width: 1.4,
    },
    {
      id: "window_balcony",
      name: "阳台推拉门",
      wallId: "wall_living_bottom",
      distance: 1.5,
      width: 1.5,
    },
  ],
};
export function createTwoBedroomFloorplanScene() {
  return buildFloorplanScene(twoBedroomSpec, [
    furnitureItem(
      "item_master_bed",
      "zone_bedroom",
      "doubleBed",
      [1.6, 0, 4.5],
    ),
    furnitureItem(
      "item_second_bed",
      "zone_bedroom_2",
      "doubleBed",
      [7.5, 0, 3.4],
    ),
    furnitureItem("item_living_sofa", "zone_living", "sofa", [4.4, 0, 3.8]),
    furnitureItem("item_kitchen", "zone_kitchen", "kitchen", [1.8, 0, 7.4]),
  ]);
}
